name: openswitch
version: 0.1.0
summary: OpenSwitch Network Operating System
description: A standalone version of OpenSwitch from openswitch.net
icon: openswitch/src/ops-webui/tools/reference/img/OpenSwitchLogo.png

apps:
  ops-sysd:
    command: usr/bin/ops-sysd
    daemon: simple

parts:
  openvswitch:
    plugin: autotools
    configflags:
      - "OPS_BUILD=1"
      - "--prefix=/usr"
      - "--exec-prefix=/usr"
      - "--libdir=/usr/lib"
      - "--enable-shared"
      - "--without-openvswitch-vtep"
      - "--without-openvswitch-testcontroller"
      - "--localstatedir=/var"
      - "--with-debug"
    # Source pre-processing required!
    # - python {src}/ops/schema/sanitize.py {src}/ops/schema/dhcp_leases.extschema  {src}/ops-openvswitch/vswitchd/dhcp_leases.ovsschema
    # - python {src}/ops/schema/sanitize.py {src}/ops/schema/vswitch.extschema  {src}/ops-openvswitch/vswitchd/vswitch.ovsschema
    # - cp {src}/ops/schema/configdb.ovsschema {src}/ops-openvswitch/vswitchd/configdb.ovsschema
    # - cp {src}/ops/schema/*.xml {src}/ops-openvswitch/vswitchd/
    source: ./openswitch/src/ops-openvswitch
    build-packages:
      - libltdl-dev

  # The openvswitch part generates an incorrect ./stage/usr/lib/libovsdb.la
  # This part fixes the libovsdb.la so libtool will succeed in ops-cli.
  fixup-ops-openvswitch-libs:
    plugin: make
    source: ./fixups
    after: [ openvswitch ]
    before: [ ops-cli ]

  ops-utils:
    plugin: cmake
    configflags:
      - "-DCMAKE_C_FLAGS=-DOPS"
      - "-DCMAKE_CXX_FLAGS=-DOPS"
      - "-DCMAKE_BUILD_TYPE=Debug"
      - "-DCMAKE_C_FLAGS_DEBUG=-DO0"
      - "-DCMAKE_CXX_FLAGS_DEBUG=-DO0"
    source: ./openswitch/src/ops-utils
    after: [ openvswitch ]

  gtest:
    plugin: cmake
    source: https://github.com/lool/googletest.git
    source-type: git

  ops-config-yaml:
    plugin: cmake
    source: ./openswitch/src/ops-config-yaml
    after: [gtest]
    build-packages:
        # if [ ! -e /usr/include/linux/i2c-dev-user.h ] ; then
        #   sudo ln -s /usr/include/linux/i2c-dev.h /usr/include/linux/i2c-dev-user.h
        # fi
      - libyaml-cpp0.3-dev
      - libi2c-dev

  ops-cli:
    plugin: autotools
    configflags:
      - "CFLAGS=-DOPS"
      - "--disable-silent-rules"
      - "--enable-user=root"
      - "--enable-group=root"
      - "--enable-ovsdb"
      - "--enable-vtysh"
      - "--enable-shared"
    source: ./openswitch/src/ops-cli
    after: [ openvswitch, fixup-ops-openvswitch-libs ]

  ops-aaa-utils:
    plugin: python2
    source: ./openswitch/src/ops-aaa-utils

  ops-arpmgrd:
    plugin: cmake
    configflags:
      - "-DCMAKE_C_FLAGS=-DOPS"
      - "-DCMAKE_CXX_FLAGS=-DOPS"
      - "-DCMAKE_BUILD_TYPE=Debug"
      - "-DCMAKE_C_FLAGS_DEBUG=-DO0"
      - "-DCMAKE_CXX_FLAGS_DEBUG=-DO0"
    source: ./openswitch/src/ops-arpmgrd
    after: [ openvswitch ]

  ops-cfgd:
    plugin: python2
    source: ./openswitch/src/ops-cfgd

  ops-fand:
    plugin: cmake
    configflags:
      - "-DCMAKE_C_FLAGS=-DOPS"
      - "-DCMAKE_CXX_FLAGS=-DOPS"
      - "-DCMAKE_BUILD_TYPE=Debug"
      - "-DCMAKE_C_FLAGS_DEBUG=-DO0"
      - "-DCMAKE_CXX_FLAGS_DEBUG=-DO0"
    source: ./openswitch/src/ops-fand
    after: [ openvswitch, ops-cli, ops-config-yaml ]

  ops-intfd:
    plugin: cmake
    configflags:
      - "-DCMAKE_C_FLAGS=-DOPS"
      - "-DCMAKE_CXX_FLAGS=-DOPS"
      - "-DCMAKE_BUILD_TYPE=Debug"
      - "-DCMAKE_C_FLAGS_DEBUG=-DO0"
      - "-DCMAKE_CXX_FLAGS_DEBUG=-DO0"
    source: ./openswitch/src/ops-intfd
    after: [ openvswitch, ops-config-yaml, ops-utils ]

  ops-ledd:
    plugin: cmake
    configflags:
      - "-DCMAKE_C_FLAGS=-DOPS"
      - "-DCMAKE_CXX_FLAGS=-DOPS"
      - "-DCMAKE_BUILD_TYPE=Debug"
      - "-DCMAKE_C_FLAGS_DEBUG=-DO0"
      - "-DCMAKE_CXX_FLAGS_DEBUG=-DO0"
    source: ./openswitch/src/ops-ledd
    after: [ openvswitch, ops-cli, ops-config-yaml ]

  ops-pmd:
    plugin: cmake
    configflags:
      - "-DCMAKE_C_FLAGS=-DOPS"
      - "-DCMAKE_CXX_FLAGS=-DOPS"
      - "-DCMAKE_BUILD_TYPE=Debug"
      - "-DCMAKE_C_FLAGS_DEBUG=-DO0"
      - "-DCMAKE_CXX_FLAGS_DEBUG=-DO0"
    source: ./openswitch/src/ops-pmd
    after: [ openvswitch, ops-config-yaml ]

  ops-powerd:
    plugin: cmake
    configflags:
      - "-DCMAKE_C_FLAGS=-DOPS"
      - "-DCMAKE_CXX_FLAGS=-DOPS"
      - "-DCMAKE_BUILD_TYPE=Debug"
      - "-DCMAKE_C_FLAGS_DEBUG=-DO0"
      - "-DCMAKE_CXX_FLAGS_DEBUG=-DO0"
    source: ./openswitch/src/ops-powerd
    after: [ openvswitch, ops-cli, ops-config-yaml ]

  ops-portd:
    plugin: cmake
    configflags:
      - "-DCMAKE_C_FLAGS=-DOPS"
      - "-DCMAKE_CXX_FLAGS=-DOPS"
      - "-DCMAKE_BUILD_TYPE=Debug"
      - "-DCMAKE_C_FLAGS_DEBUG=-DO0"
      - "-DCMAKE_CXX_FLAGS_DEBUG=-DO0"
    source: ./openswitch/src/ops-portd
    after: [ openvswitch ]

  ops-restd:
    plugin: python2
    source: ./openswitch/src/ops-restd
    python-pkgs:
      - tornado
      - certifi
      - inflect
      - backports_abc

#  ops-switchd-opennsl-plugin:
#    plugin: cmake
#    configflags:
#      - "-DCMAKE_C_FLAGS=-DOPS"
#      - "-DCMAKE_CXX_FLAGS=-DOPS"
#      - "-DCMAKE_BUILD_TYPE=Debug"
#      - "-DCMAKE_C_FLAGS_DEBUG=-DO0"
#      - "-DCMAKE_CXX_FLAGS_DEBUG=-DO0"
#    source: ./openswitch/src/ops-switchd-opennsl-plugin
#    after: [ openvswitch ]

  ops-sysd:
    plugin: cmake
    configflags:
      - "-DCMAKE_C_FLAGS=-DOPS"
      - "-DCMAKE_CXX_FLAGS=-DOPS"
      - "-DCMAKE_BUILD_TYPE=Debug"
      - "-DCMAKE_C_FLAGS_DEBUG=-DO0"
      - "-DCMAKE_CXX_FLAGS_DEBUG=-DO0"
    build-packages:
      - zlib1g-dev
    source: ./openswitch/src/ops-sysd
    after: [ openvswitch, ops-config-yaml, ops-utils ]

  ops-tempd:
    plugin: cmake
    configflags:
      - "-DCMAKE_C_FLAGS=-DOPS"
      - "-DCMAKE_CXX_FLAGS=-DOPS"
      - "-DCMAKE_BUILD_TYPE=Debug"
      - "-DCMAKE_C_FLAGS_DEBUG=-DO0"
      - "-DCMAKE_CXX_FLAGS_DEBUG=-DO0"
    source: ./openswitch/src/ops-tempd
    after: [ openvswitch, ops-cli, ops-config-yaml ]

  ops-vland:
    plugin: cmake
    configflags:
      - "-DCMAKE_C_FLAGS=-DOPS"
      - "-DCMAKE_CXX_FLAGS=-DOPS"
      - "-DCMAKE_BUILD_TYPE=Debug"
      - "-DCMAKE_C_FLAGS_DEBUG=-DO0"
      - "-DCMAKE_CXX_FLAGS_DEBUG=-DO0"
    source: ./openswitch/src/ops-vland
    after: [ openvswitch ]

#  ops-webui:
#    plugin: nodejs
#    source: ./openswitch/src/ops-webui
